export enum TipoErroSalvarAlteracao {
  MINIMO_1_DISCIPLINAS = 'MINIMO_1_DISCIPLINAS',
  MINIMO_2_DISCIPLINAS = 'MINIMO_2_DISCIPLINAS',
  MINIMO_3_DISCIPLINAS = 'MINIMO_3_DISCIPLINAS',
  QUEBRA_MODULO = 'QUEBRA_MODULO',
}
