// tslint:disable
const VueGtm = require("vue-gtm").default;

export default class DynatraceInstance {
  constructor() {

    if(process.env.NODE_ENV == "production")
    {
      this.initializeScritpHead();
    }
  }

  private initializeScritpHead() {    

    const scriptHead = `    
      (function(){window.dT_?window.console&&window.console.log("Duplicate agent injection detected, turning off redundant initConfig."):navigator.cookieEnabled&&(window.dT_||(window.dT_={cfg:"app=15c4962bc54f6040|cors=1|srms=1,1,,,|uxrgcm=100,25,300,3;100,25,300,3|featureHash=A2SVfqr|dpvc=1|lastModification=1549908744249|dtVersion=10159181221094224|reportUrl=https://bf25243htd.bf.dynatrace.com/bf|tp=500,50,0,1|rdnt=1|uxrgce=1|featureHash=A2SVfqr|agentUri=https://js-cdn.dynatrace.com/jstag/157944990f8/ruxitagent_A2SVfqr_10159181221094224.js|auto=|domain=|rid=RID_|rpid=|app=15c4962bc54f6040"}));}).call(this);

      (function(){(function(){function Cb(){return ga?new ga:ha?new ha("MSXML2.XMLHTTP.3.0"):e.XMLHttpRequest?new e.XMLHttpRequest:new e.ActiveXObject("MSXML2.XMLHTTP.3.0")}function Db(){ha=ga=void 0}function Eb(){try{Fb.apply(e.parent,arguments)}catch(a){}}function Gb(){try{Hb.apply(e.top,arguments)}catch(a){}}function Ib(a){var b=Array.prototype.slice.call(arguments,1);try{Jb.apply(a,b)}catch(c){}}function Kb(a){var b=Array.prototype.slice.call(arguments,1);try{Lb.apply(a,b)}catch(c){}}function q(){var a=0;try{a=
      e.performance.timing.navigationStart+Math.floor(e.performance.now())}catch(b){}return 0>=a||isNaN(a)||!isFinite(a)?(new Date).getTime():a}function Ca(a,b){function c(){delete U[m];a.apply(this,arguments)}for(var d=[],f=2;f<arguments.length;f++)d[f-2]=arguments[f];var m;"apply"in ia?m=ia.apply(e,[c,b].concat(d)):m=ia(c,b);U[m]=!0;return m}function Za(a){delete U[a];"apply"in F?F.call(e,a):F(a)}function l(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];a.push.apply(a,b)}function $a(a){l(Da,
      a)}function Mb(){return Da}function Nb(a,b){return ab(a,b)}function Ob(a,b){a=new Pb([a],{type:b});return Qb(a)}function Rb(a,b){return V?new V(a,b):void 0}function Sb(a){"function"===typeof a&&l(ja,a)}function Tb(){return ja}function Ub(){return Ea}function bb(a){return function(){for(var b=[],c=0;c<arguments.length;c++)b[c]=arguments[c];if("number"!==typeof b[0]||!U[b[0]])try{return a.apply(this,b)}catch(d){return a(b[0])}}}function Vb(){W&&(e.clearTimeout=F,e.clearInterval=Fa,W=!1)}function v(){return e.dT_}
      function G(a,b){return isNaN(a)||isNaN(b)?0:Math.floor(Math.random()*(b-a+1))+a}function H(a,b){return parseInt(a,b||10)}function h(a,b,c){void 0===c&&(c=0);var d=-1;b&&a&&a.indexOf&&(d=a.indexOf(b,c));return d}function cb(a){return document.getElementsByTagName(a)}function db(a){var b=a.length;if("number"===typeof b)a=b;else{for(var b=0,c=2048;a[c-1];)b=c,c+=c;for(var d=7;1<c-b;)d=(c+b)/2,a[d-1]?b=d:c=d;a=a[d]?c:b}return a}function Wb(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var d=
      a.charAt(c);l(b,Xb[d]||d)}return b.join("")}function ka(a){if(!a)return"";var b=e.crypto||e.msCrypto;if(b){var c=new Int8Array(a);b.getRandomValues(c)}else for(c=[],b=0;b<a;b++)c.push(G(0,32));a=[];for(b=0;b<c.length;b++){var d=Math.abs(c[b]%32);a.push(String.fromCharCode(d+(9>=d?48:55)))}return a.join("")}function Yb(){return y}function Zb(){return eb}function $b(){return fb}function ac(){return la}function gb(){return"dtAdk"}function bc(){return I}function hb(a){var b={};a=a.split("|");for(var c=
      0;c<a.length;c++){var d=a[c].split("=");2===d.length&&(b[d[0]]=decodeURIComponent(d[1].replace(/\\+/g," ")))}return b}function Ga(){var a=k("csu");return(a.indexOf("dbg")===a.length-3?a.substr(0,a.length-3):a)+"_"+k("app")+"_Store"}function X(a,b,c){b=b||{};a=a.split("|");for(var d=0;d<a.length;d++){var e=a[d],f=h(a[d],"=");-1===f?b[e]="1":(e=a[d].substring(0,f),b[e]=a[d].substring(f+1,a[d].length))}!c&&(c=b,a=c.spc)&&(d=document.createElement("textarea"),d.innerHTML=a,c.spc=d.value);return b}function J(a){return a in
      f?f[a]:ma[a]}function n(a){a=J(a);return"false"===a||"0"===a?!1:!!a}function na(a){var b=H(J(a));isNaN(b)&&(b=ma[a]);return b}function k(a){return String(J(a)||"")}function cc(a,b){f[a]=b}function dc(a){return f=a}function ib(a){var b=location.hostname;return b&&a?b===a||-1!==b.indexOf("."+a,b.length-("."+a).length):!0}function Ha(a){f[a]=0>h(f[a],"#"+a.toUpperCase())?f[a]:""}function jb(a){var b=a.agentUri;b&&-1<h(b,"_")&&(b=/([a-zA-Z]*)[0-9]{0,4}_([a-zA-Z_0-9]*)_[0-9]+/g.exec(b))&&b.length&&2<b.length&&
      (a.csu=b[1],a.featureHash=b[2])}function kb(a,b){ib(f.domain||"")||(f.domainOverride=location.hostname+","+f.domain,delete f.domain);f.pVO&&(a.pVO=f.pVO);b||(a.bp=a.bp||ma.bp,1===g&&a.bp1&&(a.bp=1),a.bp2&&(a.bp=2),4!==a.bp||e.JSON||(a.bp=1))}function ec(){return f}function oa(a,b){try{var c=Y;c&&c.setItem(a,b)}catch(d){}}function Z(a){try{var b=Y;if(b)return b.getItem(a)}catch(c){}return null}function Ia(a){try{var b=Y;b&&b.removeItem(a)}catch(c){}}function pa(a,b){if(K()&&(!v().v||aa))return a.apply(this,
      b||[])}function K(){return!n("coo")||n("cooO")||aa}function p(a){document.cookie=a+'="";path=/'+(k("domain")?";domain="+k("domain"):"")+"; expires=Thu, 01 Jan 1970 00:00:01 GMT;"}function qa(a,b,c){var d=1,e=0;do document.cookie=a+'=""'+(b?";domain="+b:"")+";path="+c.substr(0,d)+"; expires=Thu, 01 Jan 1970 00:00:01 GMT;",d=c.indexOf("/",d),e++;while(-1!==d&&5>e)}function z(a){var b=document.cookie;if(!b)return"";var c=a+"=";a=h(b,c);if(0>a)return"";for(;0<=a;)if(a&&" "!==b.charAt(a-1)&&";"!==b.charAt(a-
      1))a=h(b,c,a+c.length);else return c=a+c.length,a=h(b,";",a),0<=a?b.substring(c,a):b.substr(c);return""}function fc(a,b,c,d){b||0===b?(b=(""+b).replace(/[;\\n\\r]/g,"_"),a=a+"="+b+";path=/"+(k("domain")?";domain="+k("domain"):""),c&&(a+=";expires="+c.toUTCString()),d&&(a+=";Secure"),document.cookie=a):p(a)}function L(a,b,c,d){pa(fc,[a,b,c,d])}function lb(a){var b=/^[0-9A-Za-z_=:\\$\\+\\/\\.\\-\\*%\\|]*$/.test(a);return 0===g&&(0>=h(a,"$")&&-1===h(a,"=srv=")||a&&2<a.split("$").length)?!1:b}function mb(){var a=
      z(y);return a&&lb(a)?a:""}function Ja(a){L(y,a,void 0,n("ssc"))}function M(a){return 32===a.length||12>=a.length?a:""}function ra(a){return!isNaN(a)&&3>=a.length?a:""}function nb(a){var b={sessionId:"",b:""},c=h(a,"|"),d=a;-1!==c&&(d=a.substring(0,c));c=h(d,"$");-1!==c?(b.sessionId=M(d.substring(c+1)),b.b=ra(d.substring(0,c))):b.sessionId=M(d);return b}function ob(a){var b={sessionId:"",b:""};a=a.split("=");if(2<a.length&&!(a.length%2)){var c=Number(a[1]);if(isNaN(c)||3>c)return b;for(var c={},d=
      2;d<a.length;d++)c[a[d]]=a[d+1],d++;b.sessionId=M(c.sn);c.srv&&(b.b=ra(c.srv));"1"===c.ol&&(oa("dtDisabled","true"),v().disabled=!0,v().v=!0)}return b}function C(a){var b=document.cookie?document.cookie.split(a).length-1:0;if(1<b){var c=k("domain")||e.location.hostname,d=e.location.hostname,f=e.location.pathname,m=0,g=0;r.push(a);do{var h=d.substr(m);if(h!==c||"/"!==f){qa(a,h===c?"":h,f);var l=document.cookie?document.cookie.split(a).length-1:0;l<b&&(r.push(h),b=l)}m=d.indexOf(".",m)+1;g++}while(m&&
      10>g&&1<b);k("domain")&&1<b&&qa(a,"",f)}}function gc(){C(I);C(y);C(la);C("rxvt");$a(function(a,b,c,d){0<r.length&&!b&&(a.av(d,0,"dCN",function(){return r.join(",")}),a.av(d,4,"duplicateCookieNames",function(){return r.slice()}),r=[])})}function hc(){return N}function Ka(a,b,c,d){var e=document.createElement("script");e.setAttribute("src",a);b&&e.setAttribute("defer","true");c&&(e.onload=c);d&&(e.onerror=d);e.setAttribute("crossorigin","anonymous");a=document.getElementsByTagName("script")[0];a.parentElement.insertBefore(e,
      a)}function La(a,b){return O+"/"+(b||D)+"_"+a+"_"+(na("buildNumber")||v().version)+".js"}function sa(a){K()?a():(w||(w=[]),l(w,a))}function ic(a){return pa(a)}function jc(){for(var a=0;a<w.length;a++)Ca(w[a],0);w=[];f.cooO=!0}function kc(){f.cooO=!1;p(y);p(I);p(la);p("dtSa");p(gb());0===g&&(p("rxVisitor"),p("rxvt"));try{var a=Y;a&&(0===g&&a.removeItem("rxVisitor"),a.removeItem(y));(a=Ma)&&a.removeItem(Ga())}catch(b){}}function pb(a){return(a=a||mb())?h(a,"=")?nb(a):ob(a):{sessionId:"",b:""}}function ta(a){return pb(a).b}
      function ua(a){return pb(a).sessionId}function lc(){return t}function mc(){sa(function(){ua()||Ja((0===g?-1*G(2,21)+"$":"")+ka(32));t=ta()||""})}function Na(a){try{if(e.localStorage)return e.localStorage.getItem(a)}catch(b){}return null}function Oa(a){try{e.localStorage&&e.localStorage.removeItem(a)}catch(b){}}function qb(a,b){b=va(b);for(var c=!1,d=0;d<b.length;d++)b[d].frameId===N&&(b[d].g=a,c=!0);c||l(b,{frameId:N,g:a});Pa(b)}function Pa(a,b){var c="";if(a){for(var c=[],d=0;d<a.length;d++)"-"!==
      a[d].g&&(0<d&&0<c.length&&l(c,"p"),0===g&&(l(c,t),l(c,"$")),l(c,a[d].frameId),l(c,"h"),l(c,a[d].g));0===g&&(c.length||(P&&(wa(0,!0),Qa(!1)),t=ta()||"",l(c,t),l(c,"$"),l(c,N),l(c,"h-")),l(c,"v"),l(c,b||Ra()));c=c.join("")}c||(c="-",0===g&&(P&&(wa(0,!0),Qa(!1)),t=ta()||"",c=t+"$"+N+"h-v"+(b||Ra())));L(I,c,void 0,n("ssc"))}function va(a){var b=z(I),c=[];if(b&&"-"!==b)for(var b=b.split("p"),d=0;d<b.length;d++){var e=b[d].split("h");if(2===e.length&&e[0]&&e[1]){var f=e[0];if(0===g&&(f&&0<=h(f,"$")&&(f=
      f.split("$")[1]),0<=h(e[1],"v"))){var k=e[1].split("v");if(2===k.length){var n=k[1];e[1]=k[0]}}if(!(k=a)){var k=H(f.split("_")[0]),p=q()%Sa;p<k&&(p+=Sa);k=k+9E5>p}k&&l(c,{frameId:f,g:e[1]})}}if(0===g)for(a=0;a<c.length;a++)c[a].visitId=n||"";return c}function Ra(){return Ta()||wa(0,!0)}function Ta(){var a=va(!0);if(!(Q()<=q())){xa(!1);if(a&&1<=a.length)return a[0].visitId||"";(a=Na(A))||(a=Z(A));return a||""}return""}function xa(a){var b=q(),c=rb().j;a&&(c=b);sb(b+tb+"|"+c);ub()}function vb(a){a||
      (a=G(1,1E6));var b=ua()||"";b||(b=(0===g?-1*G(2,21)+"$":"")+ka(32),Ja(b),b=ua(b)||"");a=""+a;for(var c=a.length,d=[],e=0;e<b.length;e++)d[e]=String.fromCharCode(65+Math.abs((b.charCodeAt(e)^a.charCodeAt(e%c))%26));b=d.join("");for(a=0;a<R.length;a++)R[a](b);return b}function Ua(a){var b=va(!1);Pa(b,a);ba(A,a);xa(!0)}function wa(a,b){b&&(S=!0);a=vb(q());Ua(a);return a}function nc(a){R.push(a)}function ub(){ca&&Za(ca);ca=Ca(wb,Q()-q())}function wb(){if(Q()<=q()&&K()){var a=vb(q());Ua(a);return!0}sa(ub);
      return!1}function sb(a){L("rxvt",a,void 0,n("ssc"));ba("rxvt",a)}function ba(a,b){if(n("dpvc")||n("pVO"))oa(a,b),Oa(a);else{try{e.localStorage&&e.localStorage.setItem(a,b)}catch(c){}Ia(a)}}function xb(){var a=z("rxvt");a||(a=Na("rxvt")||"")||(a=Z("rxvt")||"");return a}function yb(){var a=Ta()||"";ba(A,a);a=xb();sb(a)}function rb(){var a={m:0,j:0},b=xb();if(b)try{var c=b.split("|");2===c.length&&(a.m=parseInt(c[0],10),a.j=parseInt(c[1],10))}catch(d){}return a}function Q(){var a=rb();return Math.min(a.m,
      a.j+zb)}function oc(a){tb=a}function Qa(a){void 0===a&&(a=!0);P=a}function pc(){var a=S;S=!1;return a}function qc(){wb()||xa(!1)}function Va(){var a=z("rxVisitor");if(!a||a.length&&a.length!==da)a=Z("rxVisitor"),a&&a.length===da||(Ab=!0,a=q()+"",a+=ka(da-a.length));var b=a;if(!n("dpvc")&&!n("pVO")){var c=new Date;c.setFullYear(c.getFullYear()+2)}L("rxVisitor",b,c,n("ssc"));oa("rxVisitor",b);return a}function rc(){return Ab}function sc(a){var b=z("rxVisitor");p("rxVisitor");Ia("rxVisitor");L("rxVisitor",
      b);f.pVO=!0;if(a)try{e.localStorage&&e.localStorage.setItem(Wa,"1")}catch(c){}yb()}function tc(){Oa(Wa);n("pVO")&&(f.pVO=!1,Va());yb()}var B=window;if(!B.dT_||!B.dT_.cfg||"string"!=typeof B.dT_.cfg||B.dT_.initialized)B.console&&B.console.log("Initconfig not found or agent already initialized! This is an injection issue.");else if(!(navigator.userAgent&&0<=navigator.userAgent.indexOf("RuxitSynthetic"))){var e="undefined"!==typeof window?window:self,ga,ha,ia,ab,Jb=e.postMessage,V=e.Worker,Pb=e.Blob,
      Qb=e.URL&&e.URL.createObjectURL,Lb=e.Worker&&e.Worker.prototype.postMessage,Fb=e.parent.postMessage,Hb=e.top.postMessage,F,Fa,W=!1,Da,ja=[],Ea,Ma,Y,U={},g,ma,Xb=new (function(){return function(){this["!"]="%21";this["~"]="%7E";this["*"]="%2A";this["("]="%28";this[")"]="%29";this["'"]="%27";this.$="%24";this[";"]="%3B";this[","]="%2C"}}()),I="dtPC",y="dtCookie",eb="x-dtpc",fb="x-dtreferer",la="dtLatC",f={},aa=!!navigator.userAgent&&0<=navigator.userAgent.indexOf("RuxitSynthetic"),r=[],N,Sa=6E8,Bb,
      O,D,uc={childList:!0,subtree:!0,attributes:!0,attributeOldValue:!0},vc=["_DT_RENDERING_"],w=[],t,A="rxvisitid",ca,tb=18E5,zb=216E5,S=!1,R=[],P=!1,Wa="dt-pVO",da=45,Ab=!1;(function(a){try{g=a;ga=e.XMLHttpRequest;ha=e.ActiveXObject;ia=e.setTimeout;ab=e.setInterval;W||(F=e.clearTimeout,Fa=e.clearInterval);if(!navigator.cookieEnabled)return!1;e.dT_={version:"10159181221094224",cfg:e.dT_?e.dT_.cfg:"",ica:1,disabled:!1,v:!1,gx:Cb,cx:Db,mp:Eb,mtp:Gb,mi:Ib,mw:Kb,gAST:Ub,ww:Rb,stu:Ob,nw:q,apush:l,st:Ca,si:Nb,
      aBPSL:$a,gBPSL:Mb,aBPSCC:Sb,gBPSCC:Tb,buildType:0===g?"dynatrace":"appmon",gSSV:Z,sSSV:oa,rSSV:Ia,rvl:Oa,pn:H,iVSC:lb,p3SC:ob,pLSC:nb,io:h,dC:p,sC:L,esc:Wb,gSId:ta,gDtc:ua,gSC:mb,sSC:Ja,gC:z,cRN:G,cRS:ka,gEL:db,gEBTN:cb,gSCN:Yb,gPCHN:Zb,gRHN:$b,gPCCN:bc,gLCN:ac,gMSIDCN:gb,cfgO:ec,pCfg:hb,pCSAA:X,cFHFAU:jb,sCD:kb,bcv:n,ncv:na,scv:k,stcv:cc,rplC:dc,cLSCK:Ga,gFId:hc,gBAU:La,iS:Ka,eWE:sa,oEIE:ic,oEIEWA:pa,eA:jc,dA:kc,gcSId:lc,iNV:rc,gVID:Va,dPV:sc,ePV:tc,sVIdUP:Qa,sVTT:oc,sVID:Ua,rVID:Ta,gVI:Ra,gNVId:wa,
      gARnVF:pc,cAUV:qc,uVT:xa,aNVL:nc,gPC:va,cPC:qb,sPC:Pa,clB:Vb,ct:Za};try{Ma=e.localStorage,Y=e.sessionStorage}catch(ya){}Ea=q();Da=[];U={};W||(e.clearTimeout=bb(F),e.clearInterval=bb(Fa),W=!0);N=Ea%Sa+"_"+H(G(0,1E3)+"");ma={ade:"",agentLocation:"",agentname:"",agentUri:"",uana:"data-dtname,data-dtName",app:"",async:!1,auto:!1,bandwidth:"300",bp1:!1,bp2:!1,bp:0===g?1:2,bs:!1,buildNumber:0,coo:!1,cooO:!1,cors:!1,csu:"",cux:!1,dataDtConfig:"",debugName:"",disableCookieManager:!1,disableLogging:!1,dmo:!1,
      dpvc:!1,disableXhrFailures:!1,domain:"",domainOverride:"",doNotDetect:"",dsndb:!1,dsss:!1,euf:!1,evl:"",extblacklist:"",exteventsoff:!1,fa:!1,featureHash:"",ffi:!1,hvt:216E5,lastModification:0,imm:!1,initializedModules:"",ign:"",instr:"",lab:!1,legacy:!1,lmut:!0,lzwd:!1,lzwe:!1,md:"",name:"",mdn:5E3,mepp:10,moa:30,mrt:3,msl:3E4,mhl:4E3,ncw:!1,ntd:!1,oat:180,ote:!1,perfbv:1,pui:!1,pVO:!1,rdnt:0,reportUrl:"dynaTraceMonitor",restoreTimeline:!1,rid:"",ridPath:"",rpid:"",rt:0===g?1E4:0,rtl:0===g?0:100,
      rtp:0===g?2:1,rtt:1E3,rtu:200,rx_visitID:"",sl:100,sosi:!1,spc:"",srbbv:1,srbw:!0,srad:!0,srmr:100,srms:"1,1,,,",srsr:1E5,srtbv:1,srtd:1,srtr:500,srwo:!1,ssc:!1,st:3E3,svNB:!1,syntheticConfig:!1,tal:0,tp:"500,50,3",tt:100,tvc:3E3,uam:!1,useNewCookies:!1,uxrgce:!0,uxrgcm:"100,25,300,3;100,25,300,3",vcfi:!1,WST:!1,xb:"",xmut:!0,xt:0};a:{var b=v().cfg;f={reportUrl:"dynaTraceMonitor",initializedModules:"",csu:"dtagent",dataDtConfig:"string"===typeof b?b:""};v().cfg=f;0===g&&(f.csu="ruxitagentjs");var c=
      f.dataDtConfig;c&&-1===h(c,"#CONFIGSTRING")&&(X(c,f),Ha("domain"),Ha("auto"),Ha("app"),jb(f));var d=cb("script"),t=db(d),m=-1===h(f.dataDtConfig||"","#CONFIGSTRING")?f:null;if(0<t)for(a=0;a<t;a++)b:{var b=void 0,r=d[a],c=m;if(r.attributes){var w=f.csu+"_bootstrap.js",B=/.*\\/jstag\\/.*\\/.*\\/(.*)_bs.js$/,C=c,E=r.src,A=E&&E.indexOf(w),J=r.attributes.getNamedItem("data-dtconfig");if(J){var za=E,K=J.value,u={};f.legacy=!0;if(za){var T=/([a-zA-Z]*)[0-9]{0,4}_([a-zA-Z_0-9]*)_([0-9]+)/g.exec(za);T&&T.length&&
      (u.csu=T[1],u.featureHash=T[2],0===g&&(u.agentLocation=za.substr(0,h(za,T[1])-1),u.buildNumber=T[3]))}K&&X(K,u,!0);ib(u.domain)||(u.domainOverride=location.hostname+","+u.domain,delete u.domain);b=u;if(!c)C=b;else if(!b.syntheticConfig){m=b;break b}}b||(b=f);if(A&&0<=A){var M=A+w.length+5;b.app=E.length>M?E.substr(M):"Default%20Application"}else if(E){var P=B.exec(E);P&&(b.app=P[1])}m=C}else m=c}if(m)for(var Q in m)m.hasOwnProperty(Q)&&(d=Q,f[d]=m[d]);f.rx_visitID&&(v().rx_visitID=f.rx_visitID);var Aa=
      Ga();try{var R=(m=Ma)&&m.getItem(Aa);if(R){var ea=hb(R),ba=X(ea.config||"",ea).lastModification||"",S=f.lastModification||"",ca=H(ba.substr(0,13)),da=H(S.substr(0,13));if(!S||ca>=da)for(var Ba in ea)if(ea.hasOwnProperty(Ba)){var Aa=Ba,Xa=ea[Aa]||"";"name"===Ba?f.agentname=Xa:"config"===Ba?X(Xa,f):f[Aa]=Xa}}}catch(ya){}kb(f);try{var V=f.ign;if(V&&(new RegExp(V)).test(e.location.href)){document.dT_=e.dT_=void 0;var fa=!1;break a}}catch(ya){}f.useNewCookies&&0===g&&(I="rxpc",y="rxsession",la="rxlatency",
      eb="x-rxpc",fb="x-rxreferer");fa=!0}if(!fa)return!1;gc();try{Bb=v().disabled||!!Z("dtDisabled")}catch(ya){}O=k("agentLocation");if(!O)if(document.currentScript){var x=document.currentScript.src;if(x){var ja=-1===h(x,"_bs")&&-1===h(x,"_bootstrap")&&-1===h(x,"_complete")?1:2,Ya=x.lastIndexOf("/");for(fa=0;fa<ja&&-1!==Ya;fa++)x=x.substr(0,Ya),Ya=x.lastIndexOf("/")}O=x}else O="";D=k("agentname")||k("csu")||(0===g?"ruxitagentjs":"dtagent");"true"===z("dtUseDebugAgent")?0>D.indexOf("dbg")&&(D=k("debugName")||
      D+"dbg"):D=k("name")||D;if(!n("auto")&&!n("legacy")&&!Bb){var aa=k("agentUri")||La(k("featureHash"));n("async")||"complete"===document.readyState?Ka(aa,n("async")):document.write('<script type="text/javascript" src="'+aa+'">\\x3c/script>')}var qa=e.location.href;0===g&&-1!==h(qa,"_DT_RENDERING_")&&(v().RMOD={conf:uc,ignore:vc,ID:"_DT_RENDERING_"},O&&Ka(La("R"),!0));z(y)&&(f.cooO=!0);mc();if(0===g){var ra=!!Na(Wa);f.pVO=ra;sa(Va)}0===g&&na("hvt")&&(zb=na("hvt"));pa(qb,[1])}catch(ya){return!1}return!0})(0)||
      (delete e.dT_,e.console&&e.console.log&&e.console.log("JsAgent initCode initialization failed!"))}})();}).call(this);

    `;

    console.log(scriptHead);
    const head = document.getElementsByTagName("head")[0];

    const scriptTag = document.createElement("script");
    scriptTag.type = "text/javascript";
    scriptTag.text = scriptHead;
    head.appendChild(scriptTag);
  }
}
